import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://buscacentral.com.br';

  const staticPages = [
    '',
    '/documentos',
    '/documentos/gerador-cpf',
    '/documentos/validador-cpf',
    '/documentos/gerador-cnpj',
    '/documentos/validador-cnpj',
    '/documentos/consulta-cnpj',
    '/localizacao',
    '/localizacao/busca-cep',
    '/localizacao/distancia-cidades',
    '/localizacao/clima',
    '/financeiro',
    '/financeiro/cotacao',
    '/financeiro/criptomoedas',
    '/financeiro/criptomoedas/bitcoin',
    '/financeiro/criptomoedas/ethereum',
    '/financeiro/criptomoedas/tether',
    '/financeiro/criptomoedas/binancecoin',
    '/financeiro/criptomoedas/solana',
    '/financeiro/criptomoedas/ripple',
    '/financeiro/criptomoedas/usd-coin',
    '/financeiro/criptomoedas/dogecoin',
    '/financeiro/criptomoedas/cardano',
    '/financeiro/criptomoedas/staked-ether',
    '/financeiro/tabela-fipe',
    '/financeiro/juros-compostos',
    '/financeiro/conversor-clt-pj',
    '/financeiro/financiamento-carro',
    '/financeiro/rescisao-trabalhista',
    '/financeiro/simulador-investimentos',
    '/financeiro/salario-liquido',
    '/financeiro/ferias',
    '/financeiro/decimo-terceiro',
    '/financeiro/horas-extras',
    '/documentos/consulta-cnpj',
    '/documentos/gerador-cartao-credito',
    '/utilidades',
    '/utilidades/gerador-qr-code',
    '/utilidades/gerador-senha',
    '/utilidades/gerador-uuid',
    '/utilidades/base64',
    '/utilidades/contador-caracteres',
    '/utilidades/pix-copia-cola',
    '/utilidades/timestamp',
    '/utilidades/comparador-textos',
    '/utilidades/removedor-duplicatas',
    '/utilidades/conversor-caixa',
    '/utilidades/conversor-imagens',
    '/utilidades/seletor-cores',
    '/utilidades/extrator-emails',
    '/utilidades/whatsapp-link',
    '/utilidades/dias-uteis',
    '/utilidades/rastreio',
    '/utilidades/planejador-viagem',
    '/utilidades/formatador-codigo',
    '/utilidades/calculadora-imc',
    '/utilidades/tabela-calorias',
    '/utilidades/calculadora-porcentagem',
    '/utilidades/calculadora-desconto',
    '/utilidades/conversor-unidades',
    '/utilidades/gerador-lorem-ipsum',
    '/utilidades/sorteador',
    '/utilidades/cronometro',
    '/utilidades/json-csv',
    '/utilidades/calculadora-combustivel',
    '/utilidades/validador-email',
    '/sobre',
    '/privacidade',
    '/termos',
  ];

  return staticPages.map((page) => ({
    url: `${baseUrl}${page}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: page === '' ? 1 : 0.8,
  }));
}
